### PR TITLE
Refactor/clean up and fix types

### LINKED ISSUE #103: Resolve uncontrolled component warning
`Warning: A component is changing a controlled input to be uncontrolled. This is likely caused by the value changing from a defined to undefined, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component.`

It appears that when the input fields are being populated from the backend, they are potentially being changed from an empty string to null. I believe refactoring to make sure they never get set to null should resolve the problem. All form components are potentially affected, but Header and Contacts seems to be the source of the original warning

- [ ] Header form
- [ ] Contact Forms
- [ ] Synopsis
- [ ] Tagline and logline
- [ ] Film details

### PR DESCRIPTION
**Pull request by rachelJensen**
# Description
- Closes #103 
- Refactors buttons for HeaderImg and Poster to be single click saves
- Removes commented out and unused code

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Refactoring

## How Has This Been Tested?
- [x] Use console.log()
- [x] Dev tools / react dev tools
- [x] View in local host

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

File: src/components/AwardsPress/AwardPressForm.tsx [hunk 1]
```diff
@@ -11,11 +11,11 @@ import './AwardPress.scss';
 // import { createTheme, ThemeProvider } from '@mui/system';
 
 interface IAwardPressForm {
```
Comment (ninabrissey) [inline src/components/AwardsPress/AwardPressForm.tsx:13]: Nice Rachel! Thank you for setting these.

File: src/components/FilmPoster/FilmPosterForm.tsx [hunk 2]
```diff
@@ -44,10 +40,8 @@ const FilmPosterDisplay = ({ filmEPK, setIsEditing, isEditing }: any) => {
           type="file" 
           accept="image/*" 
         />
+        {isLoading && <p>Saving image...</p>}
         {reminder && <p>Must choose a file to save</p>}
```
Comment (ninabrissey) [inline src/components/FilmPoster/FilmPosterForm.tsx:44]: Nice additions, Rachel. This definitely helps to curate a better user experience.
