### PR TITLE
Feature/fix cookie successfully

### LINKED ISSUE #71: Login Page
`As a user, when I get to the your-epk website,
I should see a login area with an input field for my email address and password.
When I click submit, I am directed to the dashboard page where I can create or view EPKs.`

- [ ] Add personalized welcome msg to dashboard

### PR DESCRIPTION
**Pull request by rachelJensen**
# Description
Great news! We have resolved the login issues. All post, patch, delete calls should be working again after user login. The cookie has been made accessible to all fetch functions that need it. 

I also reconnected the link on the login page that takes the user directly to the dashboard. However, it is hardcoded for dashboard/1 until the registration function is up and running

- [x] what did you do?
- [x] why did you do it?

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?
- [x] Use console.log()
- [x] Dev tools / react dev tools
- [x] View in local host
- [ ] Verify acceptance criteria (if applicable)

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

Closes #71

### CODE REVIEW

File: src/components/App/App.tsx [hunk 1]
```diff
@@ -29,7 +29,7 @@ function App() {
           <LoginPage />
           {/* <Redirect to={`/dashboard/${userId}`} /> */}
         </Route>
-        <Route exact path={`/dashboard/${userId}`}>
+        <Route exact path={`/dashboard/1`}>
```
Comment (ninabrissey) [inline src/components/App/App.tsx:32]: Note - when there is time, we will make this dynamic.

**Comment by ninabrissey** [comment]
Looks good. I'll merge and add login info to README.
